<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [

            // ── Antibiotics ─────────────────────────────────────────────
            [
                'name'          => 'Amoxicillin',
                'generic_name'  => 'Amoxicillin Trihydrate',
                'brand'         => 'Amoxil',
                'category'      => 'antibiotic',
                'form'          => 'capsule',
                'strength'      => '500mg',
                'unit'          => 'capsules',
                'current_stock' => 200,
                'minimum_stock' => 50,
                'unit_price'    => 8.50,
                'description'   => 'Broad-spectrum antibiotic for dental infections, tooth abscess, and post-extraction prophylaxis.',
            ],
            [
                'name'          => 'Amoxicillin',
                'generic_name'  => 'Amoxicillin Trihydrate',
                'brand'         => 'Amoxil',
                'category'      => 'antibiotic',
                'form'          => 'capsule',
                'strength'      => '250mg',
                'unit'          => 'capsules',
                'current_stock' => 150,
                'minimum_stock' => 40,
                'unit_price'    => 5.50,
                'description'   => 'Lower-dose amoxicillin for pediatric patients or milder infections.',
            ],
            [
                'name'          => 'Metronidazole',
                'generic_name'  => 'Metronidazole',
                'brand'         => 'Flagyl',
                'category'      => 'antibiotic',
                'form'          => 'tablet',
                'strength'      => '500mg',
                'unit'          => 'tablets',
                'current_stock' => 150,
                'minimum_stock' => 30,
                'unit_price'    => 7.00,
                'description'   => 'Used for anaerobic bacterial infections, periodontal disease, and ANUG (acute necrotizing ulcerative gingivitis).',
            ],
            [
                'name'          => 'Metronidazole',
                'generic_name'  => 'Metronidazole',
                'brand'         => 'Flagyl',
                'category'      => 'antibiotic',
                'form'          => 'tablet',
                'strength'      => '250mg',
                'unit'          => 'tablets',
                'current_stock' => 100,
                'minimum_stock' => 30,
                'unit_price'    => 5.00,
                'description'   => 'Lower-dose metronidazole for mild anaerobic dental infections.',
            ],
            [
                'name'          => 'Clindamycin',
                'generic_name'  => 'Clindamycin Hydrochloride',
                'brand'         => 'Dalacin C',
                'category'      => 'antibiotic',
                'form'          => 'capsule',
                'strength'      => '300mg',
                'unit'          => 'capsules',
                'current_stock' => 80,
                'minimum_stock' => 20,
                'unit_price'    => 25.00,
                'description'   => 'Alternative antibiotic for patients allergic to penicillin. Effective against dental abscesses and osteomyelitis.',
            ],
            [
                'name'          => 'Azithromycin',
                'generic_name'  => 'Azithromycin Dihydrate',
                'brand'         => 'Zithromax',
                'category'      => 'antibiotic',
                'form'          => 'tablet',
                'strength'      => '500mg',
                'unit'          => 'tablets',
                'current_stock' => 60,
                'minimum_stock' => 15,
                'unit_price'    => 35.00,
                'description'   => 'Macrolide antibiotic used as an alternative for penicillin-allergic patients. 3-day regimen.',
            ],

            // ── Analgesics / Pain Relievers ──────────────────────────────
            [
                'name'          => 'Ibuprofen',
                'generic_name'  => 'Ibuprofen',
                'brand'         => 'Advil',
                'category'      => 'analgesic',
                'form'          => 'tablet',
                'strength'      => '400mg',
                'unit'          => 'tablets',
                'current_stock' => 300,
                'minimum_stock' => 60,
                'unit_price'    => 4.50,
                'description'   => 'NSAID for post-extraction pain, toothache, and inflammatory dental conditions.',
            ],
            [
                'name'          => 'Ibuprofen',
                'generic_name'  => 'Ibuprofen',
                'brand'         => 'Advil',
                'category'      => 'analgesic',
                'form'          => 'tablet',
                'strength'      => '200mg',
                'unit'          => 'tablets',
                'current_stock' => 200,
                'minimum_stock' => 50,
                'unit_price'    => 3.00,
                'description'   => 'Lower-dose ibuprofen for mild dental pain.',
            ],
            [
                'name'          => 'Mefenamic Acid',
                'generic_name'  => 'Mefenamic Acid',
                'brand'         => 'Ponstan',
                'category'      => 'analgesic',
                'form'          => 'capsule',
                'strength'      => '500mg',
                'unit'          => 'capsules',
                'current_stock' => 250,
                'minimum_stock' => 50,
                'unit_price'    => 6.00,
                'description'   => 'NSAID analgesic commonly prescribed for dental pain and post-procedure discomfort.',
            ],
            [
                'name'          => 'Paracetamol',
                'generic_name'  => 'Acetaminophen',
                'brand'         => 'Biogesic',
                'category'      => 'analgesic',
                'form'          => 'tablet',
                'strength'      => '500mg',
                'unit'          => 'tablets',
                'current_stock' => 400,
                'minimum_stock' => 80,
                'unit_price'    => 2.50,
                'description'   => 'Safe analgesic and antipyretic. Used for mild to moderate dental pain, especially in patients who cannot take NSAIDs.',
            ],
            [
                'name'          => 'Ketorolac',
                'generic_name'  => 'Ketorolac Tromethamine',
                'brand'         => 'Toradol',
                'category'      => 'analgesic',
                'form'          => 'tablet',
                'strength'      => '10mg',
                'unit'          => 'tablets',
                'current_stock' => 50,
                'minimum_stock' => 10,
                'unit_price'    => 18.00,
                'description'   => 'Potent NSAID for moderate to severe post-operative dental pain. Short-term use only.',
            ],

            // ── Anti-Inflammatory ────────────────────────────────────────
            [
                'name'          => 'Dexamethasone',
                'generic_name'  => 'Dexamethasone',
                'brand'         => 'Decadron',
                'category'      => 'anti_inflammatory',
                'form'          => 'tablet',
                'strength'      => '0.5mg',
                'unit'          => 'tablets',
                'current_stock' => 100,
                'minimum_stock' => 20,
                'unit_price'    => 3.50,
                'description'   => 'Corticosteroid used to reduce post-operative swelling and inflammation, especially after wisdom tooth extraction.',
            ],
            [
                'name'          => 'Prednisolone',
                'generic_name'  => 'Prednisolone',
                'brand'         => 'Pred',
                'category'      => 'anti_inflammatory',
                'form'          => 'tablet',
                'strength'      => '5mg',
                'unit'          => 'tablets',
                'current_stock' => 80,
                'minimum_stock' => 20,
                'unit_price'    => 4.00,
                'description'   => 'Oral corticosteroid for severe dental inflammation and allergic reactions.',
            ],

            // ── Anesthetics ──────────────────────────────────────────────
            [
                'name'          => 'Lidocaine HCl',
                'generic_name'  => 'Lidocaine Hydrochloride',
                'brand'         => 'Xylocaine',
                'category'      => 'anesthetic',
                'form'          => 'injection',
                'strength'      => '2% with Epinephrine 1:100,000',
                'unit'          => 'cartridges',
                'current_stock' => 100,
                'minimum_stock' => 25,
                'unit_price'    => 45.00,
                'description'   => 'Most commonly used local anesthetic in dentistry. Used for all dental procedures requiring local anesthesia.',
            ],
            [
                'name'          => 'Lidocaine HCl',
                'generic_name'  => 'Lidocaine Hydrochloride',
                'brand'         => 'Xylocaine',
                'category'      => 'anesthetic',
                'form'          => 'injection',
                'strength'      => '2% Plain (No Epinephrine)',
                'unit'          => 'cartridges',
                'current_stock' => 50,
                'minimum_stock' => 15,
                'unit_price'    => 40.00,
                'description'   => 'Epinephrine-free lidocaine for patients with cardiovascular conditions or hypertension.',
            ],
            [
                'name'          => 'Articaine HCl',
                'generic_name'  => 'Articaine Hydrochloride',
                'brand'         => 'Septocaine',
                'category'      => 'anesthetic',
                'form'          => 'injection',
                'strength'      => '4% with Epinephrine 1:100,000',
                'unit'          => 'cartridges',
                'current_stock' => 60,
                'minimum_stock' => 15,
                'unit_price'    => 55.00,
                'description'   => 'High-potency local anesthetic. Preferred for infiltration in mandibular procedures.',
            ],
            [
                'name'          => 'Benzocaine Topical',
                'generic_name'  => 'Benzocaine',
                'brand'         => 'Hurricaine',
                'category'      => 'anesthetic',
                'form'          => 'ointment',
                'strength'      => '20%',
                'unit'          => 'tubes',
                'current_stock' => 20,
                'minimum_stock' => 5,
                'unit_price'    => 120.00,
                'description'   => 'Topical anesthetic applied before injection to reduce needle insertion pain.',
            ],

            // ── Antiseptics ──────────────────────────────────────────────
            [
                'name'          => 'Chlorhexidine Gluconate',
                'generic_name'  => 'Chlorhexidine Gluconate',
                'brand'         => 'Peridex',
                'category'      => 'antiseptic',
                'form'          => 'syrup',
                'strength'      => '0.12% Mouthwash',
                'unit'          => 'bottles',
                'current_stock' => 30,
                'minimum_stock' => 10,
                'unit_price'    => 180.00,
                'description'   => 'Antimicrobial mouth rinse used after extractions, periodontal surgery, and to treat gingivitis.',
            ],
            [
                'name'          => 'Povidone-Iodine',
                'generic_name'  => 'Povidone-Iodine',
                'brand'         => 'Betadine',
                'category'      => 'antiseptic',
                'form'          => 'syrup',
                'strength'      => '10% Solution',
                'unit'          => 'bottles',
                'current_stock' => 25,
                'minimum_stock' => 8,
                'unit_price'    => 95.00,
                'description'   => 'Broad-spectrum antiseptic for wound irrigation, socket cleaning, and pre-operative site preparation.',
            ],
            [
                'name'          => 'Hydrogen Peroxide',
                'generic_name'  => 'Hydrogen Peroxide',
                'brand'         => 'Generic',
                'category'      => 'antiseptic',
                'form'          => 'syrup',
                'strength'      => '3% Solution',
                'unit'          => 'bottles',
                'current_stock' => 20,
                'minimum_stock' => 5,
                'unit_price'    => 45.00,
                'description'   => 'Mild antiseptic for wound cleaning, debridement of socket, and adjunct in periodontal treatment.',
            ],

            // ── Antifungal ───────────────────────────────────────────────
            [
                'name'          => 'Clotrimazole',
                'generic_name'  => 'Clotrimazole',
                'brand'         => 'Canesten',
                'category'      => 'antifungal',
                'form'          => 'ointment',
                'strength'      => '1% Cream',
                'unit'          => 'tubes',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit_price'    => 85.00,
                'description'   => 'Topical antifungal for oral candidiasis (thrush) and angular cheilitis.',
            ],
            [
                'name'          => 'Nystatin',
                'generic_name'  => 'Nystatin',
                'brand'         => 'Mycostatin',
                'category'      => 'antifungal',
                'form'          => 'syrup',
                'strength'      => '100,000 units/mL',
                'unit'          => 'bottles',
                'current_stock' => 12,
                'minimum_stock' => 4,
                'unit_price'    => 150.00,
                'description'   => 'Oral suspension for treatment of oral candidiasis, especially in immunocompromised patients.',
            ],

            // ── Vitamins / Supplements ───────────────────────────────────
            [
                'name'          => 'Vitamin C',
                'generic_name'  => 'Ascorbic Acid',
                'brand'         => 'Cecon',
                'category'      => 'vitamin',
                'form'          => 'tablet',
                'strength'      => '500mg',
                'unit'          => 'tablets',
                'current_stock' => 200,
                'minimum_stock' => 40,
                'unit_price'    => 3.00,
                'description'   => 'Supports tissue healing and immune function. Recommended post-extraction and after periodontal surgery.',
            ],
            [
                'name'          => 'Vitamin B Complex',
                'generic_name'  => 'B1, B2, B3, B5, B6, B12',
                'brand'         => 'Becozyme',
                'category'      => 'vitamin',
                'form'          => 'tablet',
                'strength'      => 'Standard Dose',
                'unit'          => 'tablets',
                'current_stock' => 150,
                'minimum_stock' => 30,
                'unit_price'    => 5.00,
                'description'   => 'Supports nerve health and oral tissue repair. Used as adjunct for stomatitis and glossitis.',
            ],

            // ── Other ────────────────────────────────────────────────────
            [
                'name'          => 'Tranexamic Acid',
                'generic_name'  => 'Tranexamic Acid',
                'brand'         => 'Hemostan',
                'category'      => 'other',
                'form'          => 'tablet',
                'strength'      => '500mg',
                'unit'          => 'tablets',
                'current_stock' => 60,
                'minimum_stock' => 15,
                'unit_price'    => 15.00,
                'description'   => 'Antifibrinolytic agent to control bleeding after extractions, especially in patients on anticoagulants.',
            ],
            [
                'name'          => 'Calcium Hydroxide',
                'generic_name'  => 'Calcium Hydroxide',
                'brand'         => 'Dycal',
                'category'      => 'other',
                'form'          => 'other',
                'strength'      => 'Paste',
                'unit'          => 'syringes',
                'current_stock' => 10,
                'minimum_stock' => 3,
                'unit_price'    => 280.00,
                'description'   => 'Pulp-capping material used in deep cavity preparations to stimulate secondary dentin formation.',
            ],
            [
                'name'          => 'Eugenol (ZOE)',
                'generic_name'  => 'Zinc Oxide Eugenol',
                'brand'         => 'IRM',
                'category'      => 'other',
                'form'          => 'other',
                'strength'      => 'Powder + Liquid Set',
                'unit'          => 'sets',
                'current_stock' => 8,
                'minimum_stock' => 2,
                'unit_price'    => 350.00,
                'description'   => 'Temporary filling material and sedative dressing for painful teeth. Used in dry socket (alveolar osteitis) dressing.',
            ],
            [
                'name'          => 'Diphenhydramine',
                'generic_name'  => 'Diphenhydramine Hydrochloride',
                'brand'         => 'Benadryl',
                'category'      => 'antihistamine',
                'form'          => 'tablet',
                'strength'      => '25mg',
                'unit'          => 'tablets',
                'current_stock' => 50,
                'minimum_stock' => 10,
                'unit_price'    => 5.50,
                'description'   => 'Antihistamine for allergic reactions. Also used as mild sedative for anxious dental patients.',
            ],
        ];

        foreach ($medicines as $medicine) {
            Medicine::firstOrCreate(
                [
                    'name'     => $medicine['name'],
                    'strength' => $medicine['strength'],
                    'form'     => $medicine['form'],
                ],
                array_merge($medicine, ['is_active' => true])
            );
        }

        $this->command->info('✅ ' . count($medicines) . ' dental medicines seeded.');
    }
}
