<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }

        @page { margin: 15mm 14mm; }

        body {
            font-family: 'Helvetica', 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #1e293b;
        }

        .header {
            display: flex;
            align-items: center;
            gap: 10px;
            padding-bottom: 4mm;
            border-bottom: 3px solid #0e7490;
            margin-bottom: 5mm;
        }

        .header img {
            height: 16mm;
            width: 16mm;
            object-fit: contain;
            border-radius: 50%;
            flex-shrink: 0;
        }

        .header-info { flex: 1; }

        .clinic-name {
            font-size: 14pt;
            font-weight: bold;
            color: #0e7490;
        }

        .clinic-contact {
            font-size: 8pt;
            color: #64748b;
            margin-top: 1mm;
        }

        .doc-title {
            text-align: center;
            margin: 4mm 0 6mm;
        }

        .doc-title h1 {
            font-size: 15pt;
            font-weight: bold;
            color: #0e7490;
            letter-spacing: 1px;
            text-transform: uppercase;
        }

        .doc-title .range {
            font-size: 9pt;
            color: #64748b;
            margin-top: 1mm;
        }

        .section {
            margin-bottom: 6mm;
        }

        .section-title {
            font-size: 10.5pt;
            font-weight: bold;
            color: #0e7490;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 1mm;
            margin-bottom: 2mm;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            text-align: left;
            font-size: 8.5pt;
            font-weight: bold;
            color: #475569;
            background: #f0fdfa;
            padding: 1.5mm 2mm;
            border-bottom: 1px solid #cbd5e1;
        }

        td {
            font-size: 9pt;
            padding: 1.5mm 2mm;
            border-bottom: 1px solid #e2e8f0;
        }

        .empty-row td {
            color: #94a3b8;
            font-style: italic;
        }

        .footer {
            margin-top: 8mm;
            padding-top: 3mm;
            border-top: 1px solid #cbd5e1;
            font-size: 7.5pt;
            color: #94a3b8;
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="header">
        @if ($logoDataUri)
            <img src="{{ $logoDataUri }}" alt="{{ $clinicName }}">
        @endif
        <div class="header-info">
            <div class="clinic-name">{{ $clinicName }}</div>
            <div class="clinic-contact">
                @if ($clinicAddress || $clinicCity)
                    {{ trim(($clinicAddress ?? '') . (($clinicAddress && $clinicCity) ? ', ' : '') . ($clinicCity ?? '')) }}<br>
                @endif
                @if ($clinicPhone)
                    {{ $clinicPhone }}
                @endif
            </div>
        </div>
    </div>

    <div class="doc-title">
        <h1>{{ $title }}</h1>
        <div class="range">{{ $rangeLabel }}</div>
    </div>

    @foreach ($sections as [$sectionTitle, $headers, $rows])
        <div class="section">
            <div class="section-title">{{ $sectionTitle }}</div>
            <table>
                <thead>
                    <tr>
                        @foreach ($headers as $header)
                            <th>{{ $header }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @forelse ($rows as $row)
                        <tr>
                            @foreach ($row as $cell)
                                <td>{{ $cell }}</td>
                            @endforeach
                        </tr>
                    @empty
                        <tr class="empty-row">
                            <td colspan="{{ count($headers) }}">No data in this range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    @endforeach

    <div class="footer">
        Generated by {{ $clinicName }} on {{ $generatedAt }}
    </div>

</body>
</html>
